***problem1***

In [4]:
#1
import numpy as np
empty_array=np.empty((2,2))
print(empty_array)

[[4.6910013e-310 0.0000000e+000]
 [6.5973773e-310 0.0000000e+000]]


In [23]:
#2
ones_array=np.ones((4,2))
print(all_one_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [7]:
#3
def first_array(fill_value):
  return np.full((3,2),fill_value)
first_array(6)

array([[6, 6],
       [6, 6],
       [6, 6]])

In [8]:
#4
def zeros_array(shape):
  return np.zeros_like(shape)
make_zero = np.array([[3,4,5],[4,5,6]])
zeros_array(make_zero)

array([[0, 0, 0],
       [0, 0, 0]])

In [9]:
#5
def ones_array(shape):
  return np.ones_like(shape)
make_zero = np.array([[3,4,5],[4,5,6]])
ones_array(make_zero)

array([[1, 1, 1],
       [1, 1, 1]])

In [10]:
#6
new_list = [1,2,3,4]
to_numpy = np.array(new_list)
print(to_numpy)

[1 2 3 4]


***problem 2***

In [11]:
#1
random_values = np.arange(10,49)
print(random_values)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [12]:
#2
three_matrix = np.arange(0,9).reshape(3,3)
print(three_matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
#3
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
#4
random_array = np.random.random(30)
random_mean = np.mean(random_array)
print(random_array)
print("The mean of Random Array is:",random_mean)

[0.40568144 0.32086135 0.74370851 0.18106362 0.80790411 0.28366948
 0.43344784 0.18546216 0.0700987  0.22402943 0.82824638 0.29950238
 0.78501237 0.43619431 0.68237405 0.49044983 0.65238349 0.24140491
 0.57284692 0.03958801 0.13972505 0.15388827 0.1598911  0.7797779
 0.88811801 0.83900765 0.03632428 0.08671362 0.28577129 0.59409628]
The mean of Random Array is: 0.42157475802770783


In [15]:
#5
ten_by_ten = np.random.rand(10,10)
print("The 10X10 matrix is :", ten_by_ten)
min_value = ten_by_ten.min()
max_value = ten_by_ten.max()
print("The minimum value is :", min_value)
print("The maximum value is :", max_value)
#

The 10X10 matrix is : [[0.79044983 0.9483539  0.86759685 0.67241827 0.38469827 0.21216325
  0.68501369 0.40337947 0.05695529 0.52037586]
 [0.40162499 0.86016883 0.32636363 0.13622822 0.49289992 0.81967289
  0.4790474  0.65380963 0.24106878 0.02666142]
 [0.17198124 0.12160191 0.61336135 0.73673429 0.02023282 0.7824658
  0.85848023 0.89570541 0.53293358 0.43420961]
 [0.34489303 0.52118675 0.73666362 0.25022754 0.82836215 0.80938705
  0.4296737  0.58655155 0.70913172 0.86585246]
 [0.62000833 0.71064107 0.53568319 0.10430767 0.44437601 0.94966625
  0.54669878 0.73818513 0.15861055 0.39484521]
 [0.50888965 0.13235365 0.63695275 0.48398226 0.97951875 0.25205503
  0.86202914 0.28869665 0.10034033 0.93310193]
 [0.41335614 0.26640667 0.8406226  0.85144761 0.82757574 0.5495054
  0.72295969 0.17783729 0.16724366 0.29541291]
 [0.5286672  0.33718058 0.1109888  0.03530875 0.03146345 0.72921269
  0.73911756 0.85360108 0.35213432 0.10529251]
 [0.41578382 0.16014347 0.74966653 0.47903537 0.57840936 0.3

In [17]:
#6
zero_aray = np.zeros(10)
zero_aray[4] = 1
print(zero_aray)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [16]:
#7
arr = [1,2,0,0,4,4]
reversed_array = np.flip(arr)
print(reversed_array)

[4 4 0 0 2 1]


In [18]:
#8
rr = np.ones((6,6))
arr[1:-1,1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [19]:
#9
checker_board = np.zeros((8,8))
checker_board[1::2,::2] = 1
checker_board[::2,1::2] = 1
print(checker_board)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


***problem 3***

In [21]:
from re import sub
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
# Addition of Arrays
add_arrays = x+y
print(f"The sum of the given arrays is:\n{add_arrays}")
#Subtraction of Arrays
sub_arrays = x-y
print(f"The difference of the given arrays is:\n{sub_arrays}")
#Multiplication of Arrays
multiarray = x*y
print(f"The product of the given arrays is:\n{multiarray}")
#Square of arrays
squara_array = np.square(x)
print(f"The square of the given arrays is:\n{squara_array}")
#Dot Product of v,w
dot_product1 = np.dot(v,w)
print(f"The dot product of the given arrays is:\n{dot_product1}")
# Dot Product of x,v
dot_product = np.dot(x,v)
print(f"The dot product of the given arrays is:\n{dot_product}")
#Dot product of x,y
dot_product_x_y = np.dot(x,y)
print(f"The dot product of the given arrays is:\n{dot_product_x_y}")

#Concatenate x and y along row
concat_row = np.concatenate((x,y),axis=0)
print(f"The concatenated row of the given arrays is:\n{concat_row}")

#Concatenate v and w along column
concat_col=np.concatenate((v,w))
print(f"The concatenated column of the given arrays is:\n{concat_col}")

concat_x_v = np.concatenate((x,v))
print(f"The concatenated column of the given arrays is:\n{concat_x_v}")
## Error

The sum of the given arrays is:
[[ 6  8]
 [10 13]]
The difference of the given arrays is:
[[-4 -4]
 [-4 -3]]
The product of the given arrays is:
[[ 5 12]
 [21 40]]
The square of the given arrays is:
[[ 1  4]
 [ 9 25]]
The dot product of the given arrays is:
219
The dot product of the given arrays is:
[29 77]
The dot product of the given arrays is:
[[19 22]
 [50 58]]
The concatenated row of the given arrays is:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
The concatenated column of the given arrays is:
[ 9 10 11 12]


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

***problem 4***

In [22]:
import numpy as np

# Define the matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A.A⁻¹ = I
inverse_A = np.linalg.inv(A)
AA_inv = np.dot(A, inverse_A)
identity_matrix = np.eye(A.shape[0])  # Generate a 2x2 identity matrix
print(f"A:\n{A}")
print(f"Inverse of A (A⁻¹):\n{inverse_A}")
print(f"A * A⁻¹:\n{AA_inv}")
print(f"Identity matrix (I):\n{identity_matrix}")
print(f"A * A⁻¹ equals I: {np.allclose(AA_inv, identity_matrix)}\n")

# 2. Prove AB = BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print(f"A * B:\n{AB}")
print(f"B * A:\n{BA}")
print(f"AB equals BA: {np.allclose(AB, BA)}\n")

# 3. Prove (AB)ᵀ = Bᵀ * Aᵀ
AB_T = np.transpose(AB)
BT_AT = np.dot(B.T, A.T)
print(f"(AB)ᵀ:\n{AB_T}")
print(f"Bᵀ * Aᵀ:\n{BT_AT}")
print(f"(AB)ᵀ equals Bᵀ * Aᵀ: {np.allclose(AB_T, BT_AT)}\n")

# Define matrix A and B
A_eq = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_eq = np.array([-1, -3, 9])

# Solve using inverse method
A_inv = np.linalg.inv(A_eq)
X = np.dot(A_inv, B_eq)
print(f"The solution X (using inverse method) is:\n{X}\n")

# Solve using np.linalg.solve (preferred method for numerical stability)
X_solve = np.linalg.solve(A_eq, B_eq)
print(f"The solution X (using np.linalg.solve) is:\n{X_solve}")


A:
[[3 4]
 [7 8]]
Inverse of A (A⁻¹):
[[-2.    1.  ]
 [ 1.75 -0.75]]
A * A⁻¹:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Identity matrix (I):
[[1. 0.]
 [0. 1.]]
A * A⁻¹ equals I: True

A * B:
[[23 13]
 [51 29]]
B * A:
[[36 44]
 [13 16]]
AB equals BA: False

(AB)ᵀ:
[[23 51]
 [13 29]]
Bᵀ * Aᵀ:
[[23 51]
 [13 29]]
(AB)ᵀ equals Bᵀ * Aᵀ: True

The solution X (using inverse method) is:
[ 2.  1. -2.]

The solution X (using np.linalg.solve) is:
[ 2.  1. -2.]
